<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/01/18 07:48:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=bitnami_orangehrm',
  'username' => 'bn_orangehrm',
  'password' => '364e4d405c',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
