<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/01/28 05:54:43
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'securityauthenticationconfigure' => 
  array (
    'is_secure' => true,
  ),
);
