<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/28 05:54:43
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
