all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=bitnami_orangehrm'
      username: bn_orangehrm
      password: 364e4d405c
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;port=3306;dbname=test_bitnami_orangehrm'
      username: bn_orangehrm
      password: 364e4d405c